HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Plow Whip · 无人值守控制台</title>
  <style>
    :root {
      color-scheme: dark;
      font-family: Inter,"PingFang SC","Microsoft YaHei",ui-sans-serif,system-ui,-apple-system,sans-serif;
      color:#dde4f8;background:#07090f;
      --bg:#07090f;--panel:#0f1219;--panel2:#141824;--line:#1c2236;--line2:#2b3450;
      --text:#dde4f8;--muted:#68799e;--ok:#2ecc8a;--warn:#f5c842;--danger:#ff5270;
      --accent:#6a9eff;--violet:#a07aff;
    }
    *{box-sizing:border-box} body{margin:0;min-width:320px;min-height:100vh;background:var(--bg)}
    button,input,textarea,select{font:inherit} button,select{cursor:pointer} button:disabled{cursor:not-allowed;opacity:.45}
    button{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid var(--line2);border-radius:5px;padding:8px 11px;background:#141a29;color:#aebbe0;font-size:.76rem}
    button:hover:not(:disabled){border-color:#40517d;background:#192135;color:#eef2ff} button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
    button.primary{border-color:#527ed7;background:#315faa;color:white;font-weight:650} button.ghost{background:transparent} button.danger{border-color:rgba(255,82,112,.4);background:rgba(255,82,112,.06);color:#ff8298}
    input,textarea,select{width:100%;outline:0;border:1px solid var(--line2);border-radius:5px;padding:9px 10px;background:#0b0e15;color:#d9e1f5;font-size:.76rem}
    textarea{min-height:86px;resize:vertical;line-height:1.5} code,.mono,pre{font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace}
    .topbar{height:58px;display:grid;grid-template-columns:290px minmax(280px,1fr) auto;align-items:center;gap:24px;padding:0 clamp(18px,3vw,42px);border-bottom:1px solid var(--line);background:#0a0d14}
    .brand{display:flex;align-items:center;gap:11px}.brand-mark,.metric-icon,.list-icon{display:grid;place-items:center;width:34px;height:34px;border:1px solid #2d3e66;border-radius:7px;background:#111827;color:var(--accent);font-weight:800}
    .brand strong,.brand span{display:block}.brand strong{font-size:.92rem;letter-spacing:.02em}.brand span{margin-top:2px;color:var(--muted);font-size:.69rem}
    .principle{overflow:hidden;color:#8494b9;text-align:center;text-overflow:ellipsis;white-space:nowrap;font-size:.76rem}.top-status{display:flex;justify-content:flex-end;gap:14px}
    .status-dot{display:inline-flex;align-items:center;gap:6px;color:#8a9abc;font-size:.7rem;white-space:nowrap}.status-dot::before{width:7px;height:7px;border-radius:50%;background:#59647f;content:""}.status-dot.ok::before{background:var(--ok);box-shadow:0 0 0 3px rgba(46,204,138,.08)}
    .tabs{height:43px;display:flex;align-items:stretch;gap:3px;overflow-x:auto;padding:0 clamp(18px,3vw,42px);border-bottom:1px solid var(--line);background:#0b0e15}
    .tabs button{position:relative;border:0;padding:0 13px;background:transparent;color:#69799c;white-space:nowrap}.tabs button::after{position:absolute;right:10px;bottom:-1px;left:10px;height:2px;background:transparent;content:""}.tabs button:hover{background:transparent;color:#aebbe0}.tabs button.active{color:#e8edfc}.tabs button.active::after{background:var(--accent)}
    main{width:min(1400px,calc(100% - 36px));margin:0 auto;padding:18px 0 52px}.context-bar{min-height:42px;display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:14px}
    .scope-control,.context-actions{display:flex;align-items:center;gap:9px}.scope-control span,.context-copy{color:var(--muted);font-size:.7rem;white-space:nowrap}.scope-control select{width:auto;min-width:180px}.context-actions{flex-wrap:wrap;justify-content:flex-end}
    [hidden]{display:none!important}.metrics-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-bottom:12px}.metric-card{min-height:74px;display:grid;grid-template-columns:38px minmax(0,1fr);align-items:center;gap:10px;border:1px solid var(--line);border-radius:6px;padding:12px;background:var(--panel)}
    .metric-icon{width:36px;height:36px}.metric-card span{display:block;color:#7b8caf;font-size:.68rem}.metric-card strong{display:block;margin-top:2px;color:#eff3ff;font-size:1.32rem;font-variant-numeric:tabular-nums}.metric-card small{color:#5f7095;font-size:.62rem}
    .layout{display:grid;grid-template-columns:minmax(280px,.75fr) minmax(480px,1.55fr);gap:12px}.stack{display:grid;align-content:start;gap:12px}.panel{min-width:0;border:1px solid var(--line);border-radius:7px;background:var(--panel)}
    .panel-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding:16px 18px;border-bottom:1px solid var(--line)}.panel-heading h1,.panel-heading h2{margin:4px 0 0;color:#edf1ff;font-size:1.02rem;letter-spacing:-.01em}.kicker{color:#62739a;font-size:.62rem;font-weight:700;letter-spacing:.13em;text-transform:uppercase}.muted{color:var(--muted);font-size:.7rem}
    .panel-body{padding:16px 18px}.field{display:grid;gap:6px;margin-bottom:12px}.field>span{color:#7182a7;font-size:.67rem;font-weight:650}.form-actions,.detail-actions{display:flex;align-items:center;flex-wrap:wrap;gap:8px}.notice{min-height:19px;margin:10px 0 0;color:#f6d87d;font-size:.7rem}
    .table{overflow-x:auto}.table-head,.table-row{min-width:650px;display:grid;grid-template-columns:minmax(170px,1.4fr) minmax(110px,.75fr) minmax(110px,.75fr) minmax(150px,1fr);align-items:center;gap:12px;padding:10px 14px;border-bottom:1px solid var(--line)}
    .table-head{background:#0c1018;color:#58698f;font-size:.62rem;font-weight:700}.table-row{width:100%;border-width:0 0 1px;border-radius:0;background:transparent;color:#8d9dc0;text-align:left}.table-row:hover{background:#151c2c}.table-row strong,.table-row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.table-row strong{color:#c5cfe7;font-size:.74rem}.table-row small{margin-top:3px;color:#596b91;font-size:.61rem}
    .status-pill{display:inline-flex;max-width:100%;overflow:hidden;border:1px solid #2d3853;border-radius:3px;padding:3px 6px;background:#161c2a;color:#8ea0c5;font-size:.62rem;text-overflow:ellipsis;white-space:nowrap}.status-done{border-color:rgba(46,204,138,.32);background:rgba(46,204,138,.08);color:#69dca9}.status-in_progress{border-color:rgba(106,158,255,.35);background:rgba(106,158,255,.08);color:#8bb1ff}.status-needs_decision{border-color:rgba(255,82,112,.34);background:rgba(255,82,112,.08);color:#ff8ba0}.status-pending{border-color:rgba(245,200,66,.32);background:rgba(245,200,66,.06);color:#ebcf76}
    .empty{padding:34px 18px;color:#4d5a78;text-align:center;font-size:.72rem}.search-result{display:grid;grid-template-columns:90px minmax(0,1fr) auto;gap:10px;padding:10px 0;border-bottom:1px solid var(--line);color:#8192b6;font-size:.69rem}.search-result strong{overflow-wrap:anywhere;color:#c8d2e9}.search-result code{color:#617398;font-size:.62rem}
    .page-heading{margin-bottom:12px}.page-heading h1{margin:0;color:#eef2ff;font-size:1.25rem}.page-heading .kicker+h1{margin-top:4px}.page-heading p{margin:5px 0 0;color:#6d7da0;font-size:.72rem}
    .facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-bottom:1px solid var(--line)}.facts>div{min-width:0;padding:13px 17px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.facts>div:nth-child(3n){border-right:0}.facts dt{color:#5f7095;font-size:.63rem}.facts dd{overflow:hidden;margin:5px 0 0;color:#cdd6ee;text-overflow:ellipsis;white-space:nowrap;font-size:.73rem}
    .objective{margin:0;padding:17px 18px;color:#93a2c4;font-size:.8rem;line-height:1.65;overflow-wrap:anywhere}.timeline{padding:15px 18px}.timeline-row{display:grid;grid-template-columns:110px minmax(0,1fr) auto;gap:9px;padding:9px 0;border-bottom:1px solid var(--line);color:#7788ab;font-size:.67rem}.timeline-row strong{color:#b9c4df}.timeline-row code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#65769a}
    .task-page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px}.task-page-head .page-heading{margin:0}.task-project-ref{color:#5e6e91;font-size:.68rem}
    .task-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin:12px 0;border:1px solid var(--line);border-radius:7px;background:var(--panel)}.task-stat{min-width:0;padding:13px 16px;border-right:1px solid var(--line)}.task-stat:last-child{border-right:0}.task-stat span,.task-stat strong,.task-stat small{display:block}.task-stat span{color:#65769a;font-size:.63rem}.task-stat strong{margin-top:5px;color:#e6ecfb;font-size:1.18rem;font-variant-numeric:tabular-nums}.task-stat small{margin-top:3px;color:#4e5f82;font-size:.58rem}
    .task-console{display:grid;grid-template-columns:minmax(190px,.68fr) minmax(620px,2.25fr) minmax(300px,1.05fr);align-items:stretch;gap:12px;height:calc(100vh - 235px);min-height:560px}.task-console>.panel{min-height:0;overflow:hidden}.goal-rail,.task-inspector{display:flex;min-height:0;flex-direction:column}.goal-rail-body,.task-inspector-body{min-height:0;overflow:auto}.goal-rail-body{padding:9px}.goal-summary{width:100%;justify-content:space-between;margin-bottom:8px;padding:9px 10px;background:#0c1018;text-align:left}.goal-summary.selected{border-color:#527ed7;background:#16223a}.goal-group-title{display:flex;align-items:center;justify-content:space-between;padding:8px 5px;color:#536487;font-size:.61rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.goal-list{display:grid;gap:7px}.goal-card{display:grid;width:100%;min-width:0;gap:7px;padding:10px;text-align:left}.goal-card.selected{border-color:#527ed7;background:#17233b}.goal-card>strong{display:-webkit-box;overflow:hidden;color:#d5def1;font-size:.7rem;line-height:1.45;-webkit-box-orient:vertical;-webkit-line-clamp:3}.goal-card>small{display:block;overflow:hidden;color:#607198;text-overflow:ellipsis;white-space:nowrap;font-size:.59rem}.goal-card footer{display:flex;align-items:center;justify-content:space-between;gap:6px}.goal-history-toggle{width:100%;justify-content:space-between;margin-top:10px;background:#0c1018}
    .task-board{display:flex;min-width:0;flex-direction:column}.task-board .panel-heading{flex:0 0 auto}.board-scroll{min-height:0;flex:1;overflow:auto}.swimlanes{display:grid;grid-template-columns:repeat(4,minmax(165px,1fr));min-width:660px;min-height:100%}.swimlane{display:flex;min-width:0;flex-direction:column;border-right:1px solid var(--line)}.swimlane:last-child{border-right:0}.swimlane>header{display:flex;align-items:center;justify-content:space-between;flex:0 0 auto;padding:11px 12px;border-bottom:1px solid var(--line);color:#9eadd0;font-size:.7rem}.swimlane>header b{display:grid;place-items:center;min-width:22px;height:22px;border-radius:11px;background:#171e2e;color:#dbe3f7}.swimlane-body{display:grid;align-content:start;gap:8px;min-height:100%;padding:9px}.lane-card{display:grid;width:100%;min-width:0;gap:8px;padding:10px;text-align:left}.lane-card.selected{border-color:#527ed7;background:#17233b;box-shadow:inset 2px 0 #6a9eff}.lane-card>strong{display:-webkit-box;overflow:hidden;color:#dce5f8;font-size:.72rem;line-height:1.45;-webkit-box-orient:vertical;-webkit-line-clamp:3}.lane-card>small{display:block;overflow:hidden;color:#63759c;text-overflow:ellipsis;white-space:nowrap;font-size:.6rem}.lane-card .task-card-id{color:#4f6083}.lane-card .wait{white-space:normal;display:-webkit-box;color:#d1af59;-webkit-box-orient:vertical;-webkit-line-clamp:2}.lane-card footer{display:flex;align-items:center;justify-content:space-between;gap:7px;padding-top:2px;border-top:1px solid #222b40}.lane-card footer small{overflow:hidden;color:#7284ab;text-overflow:ellipsis;white-space:nowrap;font-size:.59rem}
    .task-inspector .panel-heading{flex:0 0 auto}.task-inspector-body{flex:1}.inspector-empty{display:grid;place-items:center;min-height:320px;padding:28px;color:#53617e;text-align:center;font-size:.72rem;line-height:1.65}.inspector-title{margin:0;padding:15px 18px 4px;color:#e2e8f8;font-size:.9rem;line-height:1.45}.inspector-id{display:block;padding:0 18px 13px;color:#536487;font-size:.58rem}.section{padding:14px 16px;border-bottom:1px solid var(--line)}.section:last-child{border-bottom:0}.section h2{margin:0 0 10px;color:#d9e2f7;font-size:.76rem}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:10px}.section-heading h2{margin:0}.section-heading span{color:#536487;font-size:.58rem}.task-inspector .facts{grid-template-columns:repeat(2,minmax(0,1fr))}.task-inspector .facts>div:nth-child(3n){border-right:1px solid var(--line)}.task-inspector .facts>div:nth-child(2n){border-right:0}.task-inspector .facts>div{padding:10px 14px}.task-inspector .objective{padding:10px 16px 15px;font-size:.74rem}.task-inspector form+form{margin-top:12px}.task-inspector textarea{min-height:68px}.detail-fold{border-bottom:1px solid var(--line)}.detail-fold>summary{cursor:pointer;padding:13px 16px;color:#aebada;font-size:.72rem;font-weight:650;list-style:none}.detail-fold>summary::-webkit-details-marker{display:none}.detail-fold>summary::after{float:right;color:#526385;content:"+"}.detail-fold[open]>summary::after{content:"−"}.detail-fold .section{border-top:1px solid var(--line);border-bottom:0}.codebox{max-height:250px;overflow:auto;margin:0;border:1px solid #1d263b;border-radius:5px;padding:11px;background:#090d15;color:#94a6ca;font-size:.65rem;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}
    .session-card,.artifact-card{margin-top:8px;border:1px solid #26324d;border-radius:5px;padding:10px;background:#111725}.session-card:first-child,.artifact-card:first-child{margin-top:0}.session-card header,.artifact-card header{display:flex;align-items:center;justify-content:space-between;gap:10px}.session-card strong,.artifact-card strong{color:#dce5f8;font-size:.73rem}.session-card small,.artifact-card small{display:block;margin-top:5px;color:#617398;font-size:.61rem;overflow-wrap:anywhere}.artifact-card code{display:block;margin-top:6px;color:#788bae;font-size:.61rem;overflow-wrap:anywhere}.task-link{width:100%;justify-content:space-between;margin-top:7px;text-align:left}.task-link.selected{border-color:#527ed7;background:#17233b}.provider-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}
    .decision-context{margin:12px 0;border:1px solid #344467;border-radius:6px;padding:12px;background:#101827}.decision-context h3{margin:7px 0;color:#e8edfb;font-size:.78rem;line-height:1.5}.decision-context p{margin:7px 0;color:#aebada;font-size:.7rem;line-height:1.55}.decision-shas{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:10px 0}.decision-shas div{min-width:0;border:1px solid #26324d;border-radius:4px;padding:8px;background:#0c111b}.decision-shas span,.decision-shas code{display:block}.decision-shas span{color:#62749a;font-size:.59rem}.decision-shas code{margin-top:5px;overflow:hidden;color:#cbd6ef;text-overflow:ellipsis;font-size:.58rem}.decision-option{margin-top:7px;border-left:2px solid #4b6091;padding:7px 9px;background:#111725}.decision-option strong,.decision-option small{display:block}.decision-option strong{color:#d9e2f7;font-size:.68rem}.decision-option small{margin-top:4px;color:#788aae;font-size:.6rem;line-height:1.45}.decision-evidence{display:block;margin:9px 0;color:#65779d;font-size:.58rem;line-height:1.5;overflow-wrap:anywhere}
    .settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.setting-row{display:grid;grid-template-columns:minmax(150px,.8fr) minmax(0,1fr) 110px;gap:12px;padding:11px 18px;border-bottom:1px solid var(--line);color:#8d9dc0;font-size:.68rem}.setting-row strong{color:#c5cfe7}.setting-row code{overflow-wrap:anywhere;color:#8194bd}.library-card{margin:12px;border:1px solid #20283d;border-radius:6px;padding:13px;background:var(--panel2)}.library-card header{display:flex;align-items:center;justify-content:space-between;gap:10px}.library-card h2{margin:0;color:#e2e8fa;font-size:.82rem}.library-card code{display:block;margin-top:8px;color:#7789af;font-size:.61rem;overflow-wrap:anywhere}.library-card small{color:#617398}.ok-text{color:#69dca9!important}.warning-text{color:#f6d87d!important}
    .metrics-five{grid-template-columns:repeat(5,minmax(0,1fr))}.usage-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 28px;padding:16px 18px}.usage-grid h2{margin:0 0 8px;color:#d9e2f7;font-size:.8rem}.usage-row{display:flex;min-width:0;justify-content:space-between;gap:14px;padding:9px 0;border-bottom:1px solid var(--line);color:#8192b6;font-size:.69rem}.usage-row>span{min-width:0;overflow-wrap:anywhere}.usage-row small{display:block;margin-top:4px;color:#596b91;font-size:.6rem}.usage-row strong{flex:0 0 auto;color:#cbd5ee;font-variant-numeric:tabular-nums}
    .bar-chart{height:230px;display:flex;align-items:flex-end;gap:7px;overflow-x:auto;padding:20px 18px 12px}.bar-item{min-width:28px;flex:1;display:grid;align-content:end;gap:5px;height:100%;text-align:center}.bar-item strong{color:#9eb4e2;font-size:.58rem}.bar-item i{display:block;min-height:2px;border-radius:3px 3px 0 0;background:linear-gradient(180deg,var(--accent),#315faa)}.bar-item small{color:#5d6e92;font-size:.56rem;white-space:nowrap}
    .share-row{display:grid;grid-template-columns:minmax(120px,.7fr) minmax(160px,1fr) 90px;align-items:center;gap:12px;padding:10px 18px;border-bottom:1px solid var(--line);color:#9aabd0;font-size:.69rem}.share-track{height:7px;border-radius:4px;background:#181f30;overflow:hidden}.share-track i{display:block;height:100%;background:var(--violet)}.share-row strong{text-align:right;color:#d8e1f5;font-variant-numeric:tabular-nums}
    .ratio-grid{display:grid;grid-template-columns:repeat(4,1fr)}.ratio-grid>div{padding:16px 18px;border-right:1px solid var(--line)}.ratio-grid>div:last-child{border-right:0}.ratio-grid span,.ratio-grid strong{display:block}.ratio-grid span{color:#6f80a4;font-size:.66rem}.ratio-grid strong{margin-top:7px;color:#e5ebfa;font-size:1.05rem}
    .chat-list{max-height:520px;overflow:auto;padding:16px 18px}.chat-row{max-width:86%;margin-bottom:10px;border:1px solid #26324d;border-radius:7px;padding:11px 13px;background:#111725}.chat-row.butler{margin-left:auto;border-color:#30466f;background:#132039}.chat-row header{display:flex;justify-content:space-between;gap:12px;margin-bottom:6px;color:#6f82aa;font-size:.61rem}.chat-row p{margin:0;color:#c9d3e9;font-size:.73rem;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}
    .project-manager{margin-bottom:12px}.project-manager .panel-body{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:10px}.project-create-fields{display:grid;grid-template-columns:minmax(180px,.55fr) minmax(280px,1fr);gap:10px}.project-manager .field{margin:0}
    @media(max-width:1120px){.task-console{grid-template-columns:minmax(180px,.65fr) minmax(620px,2fr);height:auto;min-height:620px}.task-inspector{grid-column:1/-1;max-height:720px}.task-inspector .facts{grid-template-columns:repeat(3,minmax(0,1fr))}.task-inspector .facts>div:nth-child(2n){border-right:1px solid var(--line)}.task-inspector .facts>div:nth-child(3n){border-right:0}}
    @media(max-width:1050px){.topbar{grid-template-columns:250px 1fr}.principle{display:none}.metrics-strip,.metrics-five{grid-template-columns:repeat(2,1fr)}.task-console{grid-template-columns:1fr;height:auto}.goal-rail,.task-board,.task-inspector{max-height:none;min-height:0}.goal-rail-body{max-height:340px}.task-board{min-height:540px}.task-inspector{grid-column:auto}.settings-grid{grid-template-columns:1fr}}
    @media(max-width:760px){.topbar{height:auto;grid-template-columns:1fr;padding-top:12px;padding-bottom:12px}.top-status{justify-content:flex-start}.context-bar{align-items:flex-start;flex-direction:column}.context-actions{justify-content:flex-start}.layout{grid-template-columns:1fr}.project-create-fields{grid-template-columns:1fr}.task-page-head{align-items:flex-start;flex-direction:column}.task-metrics{grid-template-columns:repeat(2,1fr)}.task-stat:nth-child(2){border-right:0}.task-stat:nth-child(-n+2){border-bottom:1px solid var(--line)}.task-inspector .facts{grid-template-columns:repeat(2,1fr)}.task-inspector .facts>div:nth-child(3n){border-right:1px solid var(--line)}.task-inspector .facts>div:nth-child(2n){border-right:0}.timeline-row{grid-template-columns:90px 1fr}.timeline-row time{grid-column:2}.settings-grid{grid-template-columns:1fr}}
    @media(max-width:520px){main{width:min(100% - 22px,1400px)}.metrics-strip,.metrics-five,.task-metrics{grid-template-columns:1fr}.task-stat{border-right:0;border-bottom:1px solid var(--line)}.task-stat:last-child{border-bottom:0}.scope-control{width:100%}.scope-control select{min-width:0}.context-actions{width:100%}.facts,.usage-grid,.ratio-grid{grid-template-columns:1fr}.facts>div,.ratio-grid>div{border-right:0!important}.setting-row,.project-manager .panel-body{grid-template-columns:1fr}.top-status{gap:9px;flex-wrap:wrap}.share-row{grid-template-columns:1fr}.share-row strong{text-align:left}}
  </style>
</head>
<body>
  <header class="topbar">
    <div class="brand"><div class="brand-mark">PW</div><div><strong>Plow Whip</strong><span>无人值守控制台</span></div></div>
    <div class="principle">一条主线，一个推进器，Evidence 决定终态。</div>
    <div class="top-status"><span class="status-dot" id="health-status">控制面连接中</span><span class="status-dot ok">SQLite WAL</span><span class="status-dot ok">Cronner 应用内</span></div>
  </header>
  <nav class="tabs" aria-label="主导航">
    <button data-view="global-butler" class="active" aria-current="page">全局管家</button>
    <button data-view="project-butler" aria-current="false">项目管家</button>
    <button data-view="project" aria-current="false">项目</button>
    <button data-view="task" aria-current="false">Task</button>
    <button data-view="token" aria-current="false">Token</button>
    <button data-view="monitor" aria-current="false">Monitor</button>
    <button data-view="settings" aria-current="false">设置与资源库</button>
  </nav>
  <main>
    <div class="context-bar">
      <label class="scope-control"><span>项目范围</span><select id="project-scope"><option value="">全部项目</option></select></label>
      <div class="context-actions"><span class="context-copy" id="context-copy">读取权威状态</span><button class="ghost" id="scope-open-project" disabled>进入项目</button><button class="ghost" id="refresh">刷新</button></div>
    </div>

    <section id="global-butler">
      <div class="metrics-strip">
        <div class="metric-card"><div class="metric-icon">P</div><div><span>项目</span><strong id="metric-projects">0</strong><small>SQLite 权威记录</small></div></div>
        <div class="metric-card"><div class="metric-icon">→</div><div><span>进行中</span><strong id="metric-active">0</strong><small>pending / in_progress</small></div></div>
        <div class="metric-card"><div class="metric-icon">✓</div><div><span>已完成</span><strong id="metric-done">0</strong><small>Evidence 已通过</small></div></div>
        <div class="metric-card"><div class="metric-icon">!</div><div><span>待决定</span><strong id="metric-decision">0</strong><small>自动推进已停手</small></div></div>
      </div>
      <div class="layout">
        <div class="stack">
          <article class="panel">
            <header class="panel-heading"><div><span class="kicker">Global Butler</span><h1>全局管家</h1></div><span class="status-pill status-pending">路由到项目</span></header>
            <form class="panel-body" id="message-form">
              <label class="field"><span>项目（可选）</span><select id="project-id"><option value="">自动路由</option></select></label>
              <label class="field"><span>自然语言指令或查找</span><textarea id="message" required placeholder="写入 result.txt: 闭环完成&#10;找 result.txt 任务&#10;或：@project-alpha 实现刷新按钮"></textarea></label>
              <div class="form-actions"><button class="primary" type="submit">进入队列</button></div>
              <p class="notice" id="home-notice" role="status"></p>
            </form>
          </article>
          <article class="panel">
            <header class="panel-heading"><div><span class="kicker">Exact Search</span><h2>跨项目搜索</h2></div><span class="muted">不调用模型</span></header>
            <form class="panel-body" id="search-form"><label class="field"><span>Task / Message / Artifact</span><input id="search" required maxlength="128" placeholder="result.txt"></label><button type="submit">精确搜索</button></form>
            <div class="section" id="search-results"><div class="empty">输入索引内容开始搜索。</div></div>
          </article>
        </div>
        <article class="panel">
          <header class="panel-heading"><div><span class="kicker">Canonical Projects</span><h1>项目与当前 Task</h1></div><span class="muted" id="project-count">0 项</span></header>
          <div class="table"><div class="table-head"><span>项目</span><span>公开状态</span><span>内部阶段</span><span>最近更新</span></div><div id="project-list"><div class="empty">正在读取…</div></div></div>
        </article>
      </div>
    </section>

    <section id="project-butler" hidden>
      <div class="page-heading"><span class="kicker">Project Butler</span><h1 id="butler-title">项目管家</h1><p>只处理当前项目，消息历史保存在 SQLite；一次只接收一条主人指令。</p></div>
      <div class="layout">
        <article class="panel"><header class="panel-heading"><div><span class="kicker">Project Conversation</span><h2>最近 50 条消息</h2></div><span class="muted">Provider 物理 Session 与逻辑历史分离</span></header><div class="chat-list" id="butler-messages"><div class="empty">请先选择项目。</div></div></article>
        <article class="panel"><header class="panel-heading"><div><span class="kicker">Owner Message</span><h2>交给项目管家</h2></div><span class="status-pill status-pending">进入 SQLite</span></header><form class="panel-body" id="butler-form"><label class="field"><span>当前项目指令</span><textarea id="butler-message" required placeholder="写入 result.txt: 项目管家闭环"></textarea></label><button class="primary" type="submit">提交指令</button><p class="notice" id="butler-notice" role="status"></p></form></article>
      </div>
    </section>

    <section id="project" hidden>
      <div class="page-heading"><span class="kicker">Project Registry</span><h1 id="project-title">项目</h1><p>创建或恢复项目、进入项目、归档无活动 Task 的项目。</p></div>
      <article class="panel project-manager"><header class="panel-heading"><div><span class="kicker">Project Registry</span><h2>项目基本操作</h2></div><span class="muted">内部稳定 ID 由系统维护；工作区由 Host Bridge 白名单再次校验</span></header><form class="panel-body" id="create-project-form"><div class="project-create-fields"><label class="field"><span>项目名称</span><input id="new-project-name" required maxlength="128" placeholder="审查代码"></label><label class="field"><span>宿主工作区绝对路径（代码 Task 必填）</span><input id="new-project-path" placeholder="/Users/name/work/project"></label></div><button class="primary" type="submit">新建 / 绑定 / 恢复</button></form><p class="notice panel-body" id="project-notice" role="status"></p><div class="table"><div class="table-head"><span>项目</span><span>公开状态</span><span>内部阶段</span><span>最近更新</span></div><div id="project-page-list"><div class="empty">正在读取…</div></div></div></article>
      <div id="project-detail"><article class="panel"><div class="empty">请从全局首页选择项目。</div></article></div>
    </section>

    <section id="task" hidden>
      <div class="task-page-head"><div class="page-heading"><h1>任务工作台</h1><p>从 Goal 到 Task、执行、证据和人的决定；公开状态始终只有四个。</p></div><span class="task-project-ref mono" id="task-title">请选择项目</span></div>
      <div class="task-metrics" aria-label="任务工作台指标">
        <div class="task-stat"><span>今日 Token</span><strong id="task-today-token">0</strong><small>当前项目 · Asia/Shanghai</small></div>
        <div class="task-stat"><span>进行中 Goal</span><strong id="task-active-goals">0</strong><small>未收敛到已完成</small></div>
        <div class="task-stat"><span>活动 Task</span><strong id="task-active-count">0</strong><small>pending / in_progress / needs_decision</small></div>
        <div class="task-stat"><span>已终态 Task</span><strong id="task-terminal-count">0</strong><small>Done / Cancelled</small></div>
      </div>
      <div class="task-console">
        <aside class="panel goal-rail">
          <header class="panel-heading"><div><span class="kicker">Goal Navigator</span><h2>项目 Goal</h2></div><span class="muted" id="goal-total">0</span></header>
          <div class="goal-rail-body">
            <button class="goal-summary selected" id="goal-all"><span>全部 Task</span><b id="goal-all-count">0</b></button>
            <div class="goal-group-title"><span>进行中</span><b id="goal-active-count">0</b></div>
            <div class="goal-list" id="goal-active-list"><div class="empty">正在读取…</div></div>
            <button class="goal-history-toggle" id="goal-history-toggle"><span>已完成 Goal</span><b id="goal-done-count">0</b></button>
            <div class="goal-list" id="goal-done-list" hidden></div>
          </div>
        </aside>
        <article class="panel task-board">
          <header class="panel-heading"><div><span class="kicker">Canonical Four States</span><h2>任务泳道</h2></div><span class="muted" id="task-lane-total">0 个 Task</span></header>
          <div class="board-scroll"><div class="swimlanes">
            <section class="swimlane" data-task-lane="pending"><header><strong>待执行</strong><b id="lane-pending-count">0</b></header><div class="swimlane-body" id="lane-pending"></div></section>
            <section class="swimlane" data-task-lane="in_progress"><header><strong>进行中</strong><b id="lane-in_progress-count">0</b></header><div class="swimlane-body" id="lane-in_progress"></div></section>
            <section class="swimlane" data-task-lane="needs_decision"><header><strong>待决定</strong><b id="lane-needs_decision-count">0</b></header><div class="swimlane-body" id="lane-needs_decision"></div></section>
            <section class="swimlane" data-task-lane="done"><header><strong>已完成</strong><b id="lane-done-count">0</b></header><div class="swimlane-body" id="lane-done"></div></section>
          </div></div>
        </article>
        <aside class="panel task-inspector">
          <header class="panel-heading"><div><span class="kicker" id="inspector-kicker">Selection</span><h2 id="inspector-heading">详情</h2></div><span id="task-status" class="status-pill">—</span></header>
          <div class="task-inspector-body">
            <div class="inspector-empty" id="task-inspector-empty">从左侧选择 Goal，或从泳道选择一个 Task。<br>这里会显示驱动、决定、证据和运行事实。</div>
            <div id="goal-inspector-content" hidden>
              <h3 class="inspector-title" id="goal-detail-title">Goal</h3><code class="inspector-id" id="goal-detail-id">—</code>
              <dl class="facts" id="goal-facts"></dl>
              <p class="objective" id="goal-objective"></p>
              <div class="section"><div class="section-heading"><h2>验收条件</h2><span>GoalSpec</span></div><pre class="codebox" id="goal-acceptance">—</pre></div>
            </div>
            <div id="task-inspector-content" hidden>
              <h3 class="inspector-title" id="task-detail-title">Task</h3><code class="inspector-id" id="task-detail-id">—</code>
              <dl class="facts" id="task-facts"></dl>
              <p class="objective" id="task-objective"></p>
              <div class="section"><div class="section-heading"><h2>处理 / 驱动</h2><span>动作只入队</span></div><div class="detail-actions"><button class="primary" id="wake-task">立即唤醒</button><button class="primary" id="authorize-plan" hidden>明确授权并采用 Planner 方案</button><button class="primary" id="confirm-not-executed" hidden>确认 HostJob 未被接收</button><button class="danger" id="cancel-task">取消 Task</button><button id="rerun-task">重新执行</button></div><p class="notice" id="decision-help"></p><div class="decision-context" id="git-decision-context" hidden><span class="kicker">Why This Decision</span><h3 id="git-decision-summary">缺少可验证原因</h3><p id="git-decision-question"></p><div class="decision-shas"><div><span>本地 HEAD</span><code id="git-local-head">—</code></div><div><span>远端 HEAD</span><code id="git-remote-head">—</code></div></div><div id="git-decision-options"></div><small class="decision-evidence" id="git-decision-evidence"></small><button id="refresh-git-context">只读刷新原因与证据</button></div><div id="git-publish-recovery" hidden><p class="objective" id="git-publish-scope"></p><form id="git-new-branch-form"><label class="field"><span>保留原分支，发布到新分支</span><input id="git-new-branch" required placeholder="blue-v1"></label><button type="submit">授权发布到新分支</button></form><form id="git-force-form"><label class="field"><span>覆盖原分支：输入当前远端完整 SHA 作为 lease</span><input id="git-lease-sha" required pattern="[0-9a-f]{40}" placeholder="40 位远端 commit SHA"></label><button class="danger" type="submit">明确授权 force-with-lease</button></form></div><form id="decision-form"><label class="field"><span>主人决定</span><textarea id="decision" placeholder="只在页面给出明确问题时回答"></textarea></label><button type="submit">提交决定</button></form><form id="plan-form"><label class="field"><span>高级：更新计划（JSON）</span><textarea id="plan" placeholder='{"alternatives":[],"selected":0,"tasks":[]}'></textarea></label><button type="submit">提交计划</button></form><p class="notice" id="task-notice" role="status"></p></div>
              <details class="detail-fold" open><summary>Artifact / Evidence / Handoff</summary><div class="section" id="task-evidence"><div class="empty">—</div></div></details>
              <details class="detail-fold"><summary>HostJob / Session</summary><div class="section"><h2>HostJob</h2><div id="task-jobs"><div class="empty">—</div></div></div><div class="section"><h2>角色 / Provider / Generation</h2><div id="task-sessions"><div class="empty">—</div></div></div><div class="section"><h2>本地会话分段</h2><div id="task-session-files"><div class="empty">—</div></div></div></details>
              <details class="detail-fold"><summary>有界输出与最近事件</summary><div class="section"><h2>最后 20 行</h2><pre class="codebox" id="task-output">—</pre></div><div class="section"><h2>最近事件</h2><div id="task-events"><div class="empty">—</div></div></div></details>
            </div>
          </div>
        </aside>
      </div>
    </section>

    <section id="token" hidden>
      <div class="page-heading"><span class="kicker">Usage Ledger</span><h1>Token 计量</h1><p>Cached-input 是 Input 子集；Total = Input + Output。只计量，不参与调度或完成判断。</p></div>
      <article class="panel"><header class="panel-heading"><div><span class="kicker">All History</span><h2>全历史</h2></div><span class="muted">物理 Session 相邻累计快照差分</span></header><div class="metrics-strip metrics-five panel-body"><div class="metric-card"><div class="metric-icon">Σ</div><div><span>Total</span><strong id="token-all-total">0</strong></div></div><div class="metric-card"><div class="metric-icon">I</div><div><span>Input</span><strong id="token-all-input">0</strong></div></div><div class="metric-card"><div class="metric-icon">C</div><div><span>Cached-input</span><strong id="token-all-cached">0</strong></div></div><div class="metric-card"><div class="metric-icon">U</div><div><span>Uncached-input</span><strong id="token-all-uncached">0</strong></div></div><div class="metric-card"><div class="metric-icon">O</div><div><span>Output</span><strong id="token-all-output">0</strong></div></div></div></article>
      <article class="panel"><header class="panel-heading"><div><span class="kicker">Today · Asia/Shanghai</span><h2 id="token-today-title">今日</h2></div><span class="muted">00:00 日界</span></header><div class="metrics-strip metrics-five panel-body"><div class="metric-card"><div class="metric-icon">Σ</div><div><span>今日 Total</span><strong id="token-today-total">0</strong></div></div><div class="metric-card"><div class="metric-icon">I</div><div><span>今日 Input</span><strong id="token-today-input">0</strong></div></div><div class="metric-card"><div class="metric-icon">C</div><div><span>今日 Cached-input</span><strong id="token-today-cached">0</strong></div></div><div class="metric-card"><div class="metric-icon">U</div><div><span>今日 Uncached-input</span><strong id="token-today-uncached">0</strong></div></div><div class="metric-card"><div class="metric-icon">O</div><div><span>今日 Output</span><strong id="token-today-output">0</strong></div></div></div></article>
      <article class="panel"><header class="panel-heading"><div><span class="kicker">Visible Ratios · 非 Gate</span><h2>可见比值</h2></div><span class="muted">分母为 0 时显示 —</span></header><div class="ratio-grid"><div><span>全历史 Input / Output</span><strong id="ratio-all-io">—</strong></div><div><span>全历史 Cached / Uncached</span><strong id="ratio-all-cu">—</strong></div><div><span>今日 Input / Output</span><strong id="ratio-today-io">—</strong></div><div><span>今日 Cached / Uncached</span><strong id="ratio-today-cu">—</strong></div></div></article>
      <div class="settings-grid"><article class="panel"><header class="panel-heading"><div><span class="kicker">Last 30 Days</span><h2>Token 趋势</h2></div><span class="muted">日级 Total</span></header><div class="bar-chart" id="token-trend"><div class="empty">正在读取…</div></div></article><article class="panel"><header class="panel-heading"><div><span class="kicker">All History</span><h2>项目占比</h2></div><span class="muted">按 Total</span></header><div id="project-share"><div class="empty">正在读取…</div></div></article></div>
      <article class="panel"><header class="panel-heading"><div><span class="kicker">ModelCallLedger</span><h2>消费明细</h2></div><span class="muted">项目 / Task / model / session</span></header><div class="usage-grid"><div><h2>按项目</h2><div id="usage-projects"></div></div><div><h2>按 Task</h2><div id="usage-tasks"></div></div><div><h2>按 model</h2><div id="usage-models"></div></div><div><h2>按 session 与 Worker</h2><div id="usage-sessions"></div></div></div></article>
    </section>

    <section id="monitor" hidden>
      <div class="page-heading"><span class="kicker">Read-only Operations</span><h1>Monitor 只读</h1><p>当前权威事实与最近 20 条事件；不保存采样、不回放全历史、不推进状态。</p></div>
      <div class="metrics-strip"><div class="metric-card"><div class="metric-icon">P</div><div><span>活动项目</span><strong id="monitor-project-count">0</strong><small id="monitor-archived-count">归档 0</small></div></div><div class="metric-card"><div class="metric-icon">T</div><div><span>Task</span><strong id="monitor-task-count">0</strong><small>四态合计</small></div></div><div class="metric-card"><div class="metric-icon">↻</div><div><span>到期动作</span><strong id="monitor-due-count">0</strong><small>next_action_at</small></div></div><div class="metric-card"><div class="metric-icon">L</div><div><span>活动租约</span><strong id="monitor-lease-count">0</strong><small>项目 fencing</small></div></div><div class="metric-card"><div class="metric-icon">S</div><div><span>TaskSession</span><strong id="monitor-session-count">0</strong><small>稳定工作槽</small></div></div><div class="metric-card"><div class="metric-icon">J</div><div><span>HostJob</span><strong id="monitor-job-count">0</strong><small>真实调用事实</small></div></div><div class="metric-card"><div class="metric-icon">A</div><div><span>Artifact</span><strong id="monitor-artifact-count">0</strong><small>含 Evidence / Handoff</small></div></div></div>
      <div class="settings-grid"><article class="panel"><header class="panel-heading"><div><span class="kicker">Canonical Store</span><h2>SQLite / Cronner</h2></div><span class="status-pill status-done" id="monitor-db-status">读取中</span></header><dl class="facts" id="monitor-facts"></dl></article><article class="panel"><header class="panel-heading"><div><span class="kicker">Four States</span><h2>Task 状态</h2></div><span class="muted">活动状态 + 历史 Done</span></header><dl class="facts" id="monitor-statuses"></dl></article></div>
      <article class="panel"><header class="panel-heading"><div><span class="kicker">Provider Diagnostics</span><h2>Provider 探针</h2></div><span class="muted">结果由 Probe Task 持久化；Monitor 读取，不直接推进</span></header><div class="usage-grid" id="monitor-providers"><div class="empty">正在读取…</div></div><p class="notice panel-body" id="probe-notice"></p></article>
      <div class="settings-grid"><article class="panel"><header class="panel-heading"><div><span class="kicker">Project Snapshot</span><h2>当前项目</h2></div><span class="muted">归档项目不展开</span></header><div id="monitor-projects"><div class="empty">正在读取…</div></div></article><article class="panel"><header class="panel-heading"><div><span class="kicker">Latest 20</span><h2>生命周期事件</h2></div><span class="muted">有界观察</span></header><div class="timeline" id="monitor-events"><div class="empty">正在读取…</div></div></article></div>
    </section>

    <section id="settings" hidden>
      <div class="page-heading"><span class="kicker">Frozen Context</span><h1>设置与资源库</h1><p>TaskSession 创建时冻结实际 SHA 与生效来源；有限项目阈值通过 action 入队后由 Cronner 生效。</p></div>
      <article class="panel"><header class="panel-heading"><div><span class="kicker">Project Override</span><h2>项目阈值</h2></div><span class="muted">Project &gt; Global；不写 Secret</span></header><form class="panel-body project-create-fields" id="setting-form"><label class="field"><span>设置项</span><select id="setting-key"><option value="max_runtime_seconds">HostJob max_runtime_seconds</option><option value="stop_grace_seconds">stop_grace_seconds</option><option value="context_max_bytes">Context max bytes</option><option value="session_segment_max_bytes">Cold segment max bytes</option><option value="native_compact_input_tokens">native compact threshold</option><option value="rotation_input_tokens">generation rotation threshold</option><option value="handoff_max_bytes">handoff max bytes</option><option value="checkpoint_max_bytes">checkpoint max bytes</option><option value="monitor_tail_lines">Monitor tail lines</option><option value="monitor_tail_bytes">Monitor tail bytes</option><option value="retry_count">retry count</option><option value="retry_backoff_seconds">retry backoff seconds</option></select></label><label class="field"><span>整数值</span><input id="setting-value" type="number" min="0" step="1" required value="600"></label><button class="primary" type="submit">提交当前项目设置</button><p class="notice" id="setting-notice" role="status"></p></form></article>
      <div class="settings-grid">
        <article class="panel"><header class="panel-heading"><div><span class="kicker">Provider Pool</span><h2>项目 Provider 顺序</h2></div><span class="muted">新 TaskSession 冻结</span></header><form class="panel-body" id="provider-order-form"><label class="field"><span>角色</span><select id="provider-role"><option value="planner">planner</option><option value="fullstack">fullstack</option><option value="independent_checker">independent_checker</option><option value="provider_probe">provider_probe</option></select></label><label class="field"><span>有序候选（逗号分隔）</span><input id="provider-order" required value="codex_cli,cursor_cli,deepseek,kimi"></label><button class="primary" type="submit">提交 Provider 顺序</button><p class="notice" id="provider-order-notice" role="status"></p></form></article>
        <article class="panel"><header class="panel-heading"><div><span class="kicker">Project Rules</span><h2>项目规则</h2></div><span class="muted">版本化文件 + SHA</span></header><form class="panel-body" id="project-rule-form"><label class="field"><span>规则键</span><input id="project-rule-key" required pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,63}" placeholder="coding_convention"></label><label class="field"><span>规则正文</span><textarea id="project-rule-content" required placeholder="只写项目长期稳定、可复用的约束。"></textarea></label><button class="primary" type="submit">保存项目规则</button><p class="notice" id="project-rule-notice" role="status"></p></form></article>
      </div>
      <div class="settings-grid"><article class="panel"><header class="panel-heading"><div><span class="kicker">Effective Values</span><h2>设置</h2></div><span class="muted">来源可追溯</span></header><div id="settings-data"><div class="empty">正在读取…</div></div></article><article class="panel"><header class="panel-heading"><div><span class="kicker">File Sources</span><h2>资源库</h2></div><span class="muted">SHA-256 校验</span></header><div id="library-data"><div class="empty">正在读取…</div></div></article></div>
    </section>
  </main>
  <script>
    const views=[...document.querySelectorAll('main>section')];
    const nav=[...document.querySelectorAll('.tabs button')];
    let projects=[],currentProject=null,currentTask=null,currentGoal=null,taskBoardData=null,taskUsageData=null;
    const $=selector=>document.querySelector(selector);
    const key=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
    const labels={pending:'待执行',in_progress:'进行中',done:'已完成',needs_decision:'待决定',cancelled:'已取消'};
    const label=value=>labels[value]||value||'—';
    const time=value=>value?new Date(value*1000).toLocaleString('zh-CN',{hour12:false}):'—';
    const clear=node=>{while(node.firstChild)node.firstChild.remove()};
    const node=(tag,className,text)=>{const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=text;return element};
    const status=value=>{const element=node('span',`status-pill status-${value||''}`,label(value));return element};
    const parse=value=>{try{return JSON.parse(value)}catch{return value}};
    const projectName=id=>projects.find(item=>item.project_id===id)?.display_name||id||'—';
    const show=(name,load=true)=>{views.forEach(view=>view.hidden=view.id!==name);nav.forEach(button=>{const active=button.dataset.view===name;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false')});if(!load)return;if(name==='settings')loadSettings();if(name==='token')loadToken();if(name==='monitor')loadMonitor();if(name==='project-butler')loadButler();if(name==='task')loadTaskBoard()};
    nav.forEach(button=>button.addEventListener('click',()=>show(button.dataset.view)));
    async function api(path,options){const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body}
    function fact(term,value){const box=node('div');box.append(node('dt','',term),node('dd','mono',String(value??'—')));return box}
    function eventRows(target,events){clear(target);if(!events?.length){target.append(node('div','empty','还没有事件。'));return}events.forEach(event=>{const row=node('div','timeline-row');row.append(node('strong','',event.kind),node('code','',event.detail_json||'{}'),node('time','',time(event.created_at)));target.append(row)})}
    function renderMetrics(){const statuses=projects.map(item=>item.outcome||item.public_status);$('#metric-projects').textContent=projects.length;$('#metric-active').textContent=statuses.filter(item=>item==='pending'||item==='in_progress').length;$('#metric-done').textContent=statuses.filter(item=>item==='done').length;$('#metric-decision').textContent=statuses.filter(item=>item==='needs_decision').length}
    function renderScope(){const select=$('#project-scope'),route=$('#project-id'),open=$('#scope-open-project'),selected=currentProject||'',routeSelected=route.value;clear(select);clear(route);const all=node('option','','全部项目'),automatic=node('option','','自动路由');all.value='';automatic.value='';select.append(all);route.append(automatic);projects.forEach(project=>{for(const target of [select,route]){const option=node('option','',project.display_name||project.project_id);option.value=project.project_id;target.append(option)}});select.value=projects.some(item=>item.project_id===selected)?selected:'';route.value=projects.some(item=>item.project_id===routeSelected)?routeSelected:'';open.disabled=!select.value}
    async function loadHealth(){try{const health=await api('/health');$('#health-status').classList.toggle('ok',health.status==='ok');$('#health-status').textContent=health.status==='ok'?'控制面在线':'控制面异常'}catch{$('#health-status').classList.remove('ok');$('#health-status').textContent='控制面离线'}}
    function renderProjectList(box){clear(box);if(!projects.length){box.append(node('div','empty','还没有活动项目。可新建项目，归档项目不会在此显示。'));return}projects.forEach(project=>{const button=node('button','table-row');const identity=node('span');identity.append(node('strong','',project.display_name||project.project_id),node('small','mono',project.host_path||'未绑定代码工作区'),node('small','mono',`${project.project_id} · ${project.task_id||'等待 Task'}`));button.append(identity,status(project.outcome||project.public_status),node('span','mono',project.phase||'—'),node('span','',time(project.updated_at)));button.addEventListener('click',()=>openProject(project.project_id));box.append(button)})}
    async function loadProjects(){try{const data=await api('/api/projects');projects=data.projects||[];renderMetrics();renderScope();$('#project-count').textContent=`${projects.length} 项`;renderProjectList($('#project-list'));renderProjectList($('#project-page-list'))}catch(error){[$('#project-list'),$('#project-page-list')].forEach(box=>{clear(box);box.append(node('div','empty',error.message))})}}
    function projectView(data){
      const task=data.task,wrapper=node('div','layout'),summary=node('article','panel');
      const head=node('header','panel-heading'),heading=node('div');
      heading.append(node('span','kicker','Current Task'),node('h2','',task?'执行摘要':'暂无 Task'));
      head.append(heading,status(task?.outcome||task?.public_status));summary.append(head);
      const facts=node('dl','facts');facts.append(fact('Host 工作区',data.host_path||'未绑定'));
      if(task){facts.append(fact('Task ID',task.id),fact('公开状态',label(task.public_status)),fact('内部阶段',task.phase),fact('Spec Revision',task.spec_revision),fact('Retry',task.retry_count),fact('Outcome',label(task.outcome)));summary.append(facts);const spec=parse(task.spec_json)||{};summary.append(node('p','objective',spec.instruction||spec.content||JSON.stringify(spec)))}
      else{summary.append(facts,node('div','empty','项目已创建，尚未收到执行指令。'))}
      const actions=node('div','section');
      const butler=node('button','','打开项目管家');butler.addEventListener('click',()=>{show('project-butler');loadButler()});actions.append(butler);
      if(task){const open=node('button','primary',task.public_status==='needs_decision'?'处理待决定':'打开 Task');open.addEventListener('click',()=>openTask(task.id));actions.append(open)}
      const archive=node('button','danger','归档项目');archive.disabled=Boolean(task&&!task.outcome);archive.title=archive.disabled?'存在活动 Task，不能归档':'保留全部历史并从日常列表隐藏';archive.addEventListener('click',archiveCurrentProject);actions.append(archive);summary.append(actions);
      const timeline=node('article','panel'),timelineHead=node('header','panel-heading'),timelineTitle=node('div');timelineTitle.append(node('span','kicker','Latest 20'),node('h2','','事件时间线'));timelineHead.append(timelineTitle,node('span','muted','Monitor 只读'));timeline.append(timelineHead);const rows=node('div','timeline');eventRows(rows,data.events);timeline.append(rows);wrapper.append(summary,timeline);return wrapper
    }
    async function openProject(id){currentProject=id;$('#project-scope').value=id;show('project');$('#project-title').textContent=projectName(id);$('#context-copy').textContent=`项目 ${projectName(id)}`;const box=$('#project-detail');clear(box);box.append(node('article','panel empty','正在读取…'));try{const data=await api(`/api/projects/${encodeURIComponent(id)}`);$('#project-title').textContent=data.project_name||projectName(id);$('#context-copy').textContent=`项目 ${data.project_name||projectName(id)}`;clear(box);box.append(projectView(data));currentTask=data.task?.id||null}catch(error){clear(box);box.append(node('article','panel empty',error.message))}}
    const taskPublicStatus=item=>item?.outcome==='cancelled'?'cancelled':item?.outcome?'done':item?.public_status;
    function renderTaskMetrics(data,usage){const tasks=data.tasks||[],goals=data.goals||[],today=(usage?.today_projects||[]).find(item=>item.project_id===currentProject);$('#task-today-token').textContent=Number(today?.total_tokens||0).toLocaleString('zh-CN');$('#task-active-goals').textContent=goals.filter(item=>item.public_status!=='done').length;$('#task-active-count').textContent=tasks.filter(item=>!item.outcome).length;$('#task-terminal-count').textContent=tasks.filter(item=>item.outcome).length}
    function goalCard(goal){const button=node('button',`goal-card ${goal.id===currentGoal?'selected':''}`);button.append(node('strong','',goal.objective),node('small','mono',goal.id));const footer=node('footer');footer.append(status(goal.public_status),node('small','',`${goal.task_count} Task · Plan r${goal.plan_revision}`));button.append(footer);button.addEventListener('click',()=>openGoal(goal.id));return button}
    function renderGoalRail(data){const goals=data.goals||[],active=goals.filter(item=>item.public_status!=='done'),done=goals.filter(item=>item.public_status==='done');$('#goal-total').textContent=`${goals.length} Goal`;$('#goal-all-count').textContent=(data.tasks||[]).length;$('#goal-active-count').textContent=active.length;$('#goal-done-count').textContent=done.length;$('#goal-all').classList.toggle('selected',!currentGoal);const activeBox=$('#goal-active-list'),doneBox=$('#goal-done-list');clear(activeBox);clear(doneBox);if(!active.length)activeBox.append(node('div','empty','没有进行中的 Goal。'));else active.forEach(goal=>activeBox.append(goalCard(goal)));if(!done.length)doneBox.append(node('div','empty','还没有完成的 Goal。'));else done.forEach(goal=>doneBox.append(goalCard(goal)))}
    function renderTaskBoard(data){const all=data.tasks||[],tasks=currentGoal?all.filter(item=>item.goal_id===currentGoal):all;$('#task-lane-total').textContent=currentGoal?`${tasks.length} / ${all.length} 个 Task`:`${tasks.length} 个 Task`;for(const lane of ['pending','in_progress','needs_decision','done']){const box=$(`#lane-${lane}`),items=tasks.filter(item=>(item.outcome?'done':item.public_status)===lane).sort((left,right)=>right.updated_at-left.updated_at||right.id.localeCompare(left.id));clear(box);$(`#lane-${lane}-count`).textContent=items.length;if(!items.length){box.append(node('div','empty','暂无'));continue}items.forEach(item=>{const button=node('button',`lane-card ${item.id===currentTask?'selected':''}`),footer=node('footer');button.append(status(taskPublicStatus(item)),node('strong','',item.objective||'未命名 Task'),node('small','task-card-id mono',item.id));if(item.wait_reason)button.append(node('small','wait',item.wait_reason));footer.append(node('small','',`${item.role_key||'—'} · ${item.provider_key||'local'}`),node('small','',`${Number(item.normalized_total||0).toLocaleString('zh-CN')} Token`));button.append(footer);button.addEventListener('click',()=>openTask(item.id));box.append(button)})}}
    function renderEmptyInspector(copy='从左侧选择 Goal，或从泳道选择一个 Task。'){currentTask=null;$('#task-inspector-empty').hidden=false;$('#task-inspector-empty').textContent=copy;$('#goal-inspector-content').hidden=true;$('#task-inspector-content').hidden=true;$('#inspector-kicker').textContent='Selection';$('#inspector-heading').textContent='详情';$('#task-status').className='status-pill';$('#task-status').textContent='—'}
    function renderGoalDetail(goal){$('#task-inspector-empty').hidden=true;$('#task-inspector-content').hidden=true;$('#goal-inspector-content').hidden=false;$('#inspector-kicker').textContent='Goal Detail';$('#inspector-heading').textContent='目标';$('#task-status').className=`status-pill status-${goal.public_status}`;$('#task-status').textContent=label(goal.public_status);$('#goal-detail-title').textContent=goal.objective;$('#goal-detail-id').textContent=goal.id;const facts=$('#goal-facts');clear(facts);facts.append(fact('公开状态',label(goal.public_status)),fact('Task',goal.task_count),fact('Goal Rev',goal.spec_revision),fact('Plan Rev',goal.plan_revision),fact('已终态',goal.terminal),fact('创建时间',time(goal.created_at)));$('#goal-objective').textContent=goal.objective;$('#goal-acceptance').textContent=JSON.stringify(goal.acceptance,null,2)}
    function openGoal(id){if(!taskBoardData)return;const goal=(taskBoardData.goals||[]).find(item=>item.id===id);if(!goal)return;currentGoal=id;currentTask=null;renderGoalRail(taskBoardData);renderTaskBoard(taskBoardData);renderGoalDetail(goal);$('#context-copy').textContent=`${projectName(currentProject)} / Goal ${id}`}
    function renderArtifacts(data){const box=$('#task-evidence');clear(box);const items=[...(data.artifacts||[]),...(data.handoffs||[]).map(item=>({...item,kind:'handoff'}))];if(!items.length){box.append(node('div','empty','尚未产生 Artifact、Evidence 或 Handoff。'));return}items.forEach(item=>{const card=node('article','artifact-card');const head=node('header');head.append(node('strong','',item.kind),node('span',item.kind==='evidence'?'status-pill status-done':'status-pill',`rev ${item.revision}`));card.append(head,node('code','',item.path),node('small','mono',`sha256 ${item.sha256}`));box.append(card)})}
    function renderSessions(data){const box=$('#task-sessions');clear(box);if(!data.sessions?.length){box.append(node('div','empty','尚未创建 TaskSession。'));return}data.sessions.forEach(session=>{const usage=(data.model_usage||[]).find(item=>item.task_session_id===session.task_session_id)?.normalized_total||0;const card=node('article','session-card');const head=node('header');head.append(node('strong','',session.role_key),status(session.status==='archived'?'done':session.status));card.append(head,node('small','mono',`${session.provider_key} / ${session.model||'—'} · generation ${session.generation}`),node('small','mono',`Session ${session.task_session_id} · Worker ${session.worker_id}`),node('small','mono',`External ${session.external_session_id||'—'} · normalized ${usage}`));box.append(card)})}
    function renderSessionFiles(data){const box=$('#task-session-files');clear(box);if(!data.session_files?.length){box.append(node('div','empty','尚无本地会话分段。'));return}data.session_files.forEach(item=>{const card=node('article','session-card');card.append(node('code','',item.path),node('small','mono',`${Number(item.bytes||0).toLocaleString('zh-CN')} bytes`));box.append(card)})}
    function renderJobs(data){const box=$('#task-jobs'),active=new Set(['dispatching','running','cancelling']);clear(box);if(!data.host_jobs?.length){box.append(node('div','empty','尚无 HostJob。'));return}data.host_jobs.forEach(job=>{const card=node('article','session-card'),head=node('header'),state=job.status==='succeeded'?'done':active.has(job.status)?'in_progress':job.status==='cancelled'?'cancelled':'needs_decision';head.append(node('strong','',`#${job.sequence} · ${job.purpose}`),status(state));card.append(head,node('small','mono',`${job.task_session_id||'—'} · generation ${job.session_generation??'—'}`),node('small','mono',`${job.status} · exit ${job.returncode??'—'} · ${job.failure_code||'ok'} · ${time(job.ended_at||job.started_at)}`));box.append(card)})}
    function renderTaskDetail(data){
      const task=data.task,current=taskPublicStatus(task),spec=parse(task.spec_json)||{};
      $('#task-inspector-empty').hidden=true;$('#goal-inspector-content').hidden=true;$('#task-inspector-content').hidden=false;
      $('#inspector-kicker').textContent='Task Detail';$('#inspector-heading').textContent='任务';
      $('#task-status').className=`status-pill status-${current||''}`;$('#task-status').textContent=label(current);
      $('#task-detail-title').textContent=data.objective||'未命名 Task';$('#task-detail-id').textContent=task.id;
      const facts=$('#task-facts');clear(facts);
      facts.append(fact('公开状态',label(task.public_status)),fact('内部阶段',task.phase),fact('Spec Rev',task.spec_revision),fact('Sprint',task.sprint),fact('Role / Checker',`${task.role_key} / ${task.checker_role_key}`),fact('Workspace',data.host_path||'未绑定'),fact('Retry',task.retry_count),fact('Fault',task.fault_code),fact('Next action',`${task.next_action_kind||'—'} · ${time(task.next_action_at)}`),fact('Deadline',time(task.deadline_at)));
      $('#task-objective').textContent=data.objective||spec.instruction||spec.content||JSON.stringify(spec);
      $('#task-output').textContent=(data.last_output||[]).join('\n')||'无输出';
      $('#wake-task').disabled=!['pending','in_progress'].includes(task.public_status)||Boolean(task.outcome);
      $('#cancel-task').disabled=Boolean(task.outcome);$('#rerun-task').disabled=task.outcome!=='cancelled';
      const needs=task.public_status==='needs_decision'&&!task.outcome;
      const canAuthorize=needs&&task.phase==='plan';
      const unknownJob=needs&&task.fault_code==='unsafe_unknown'?(data.host_jobs||[]).find(job=>job.status==='dispatching'):null;
      const gitDecision=needs&&spec.kind==='git_publish'&&!unknownJob;
      const gitContext=data.decision_context||null;
      const contextComplete=gitDecision&&gitContext?.complete===true&&gitContext.spec_revision===task.spec_revision;
      const confirmButton=$('#confirm-not-executed'),gitRecovery=$('#git-publish-recovery'),contextPanel=$('#git-decision-context');
      $('#authorize-plan').hidden=!canAuthorize;$('#authorize-plan').disabled=!canAuthorize;
      confirmButton.hidden=!unknownJob;confirmButton.disabled=!unknownJob;confirmButton.dataset.jobId=unknownJob?.id||'';
      contextPanel.hidden=!gitDecision;
      $('#git-decision-summary').textContent=gitContext?.summary||'当前 Spec revision 缺少可验证的 Git 原因与证据，授权入口已锁定。';
      $('#git-decision-question').textContent=gitContext?.question||'先运行只读复核；它不会 push，也不会修改远端。';
      $('#git-local-head').textContent=gitContext?.local_head||'尚未观察';
      $('#git-remote-head').textContent=gitContext?.remote_head||'尚未观察';
      const optionBox=$('#git-decision-options');clear(optionBox);
      (gitContext?.options||[]).forEach(option=>{const card=node('div','decision-option');card.append(node('strong','',option.title),node('small','',option.effect),node('small','',`${option.risk} · 需要：${option.required_input}`));optionBox.append(card)});
      $('#git-decision-evidence').textContent=(gitContext?.evidence||[]).map(item=>item.kind==='host_job'?`HostJob ${item.id}${item.returncode===undefined?'':` exit ${item.returncode}`}`:`Artifact ${item.path}`).join(' · ')||'尚无当前 revision 的只读 Evidence';
      $('#refresh-git-context').disabled=!gitDecision;
      $('#refresh-git-context').textContent=contextComplete?'重新只读复核远端':'只读刷新原因与证据';
      gitRecovery.hidden=!contextComplete;
      $('#git-publish-scope').textContent=contextComplete?`目标 ${gitContext.remote_ssh||spec.remote_ssh} / ${gitContext.branch||spec.branch}。授权绑定本地 ${gitContext.local_head} 与当前决策证据；远端变化时安全拒绝。`:'';
      const branchInput=$('#git-new-branch');
      if(contextComplete&&branchInput.dataset.taskId!==task.id){branchInput.value=`${gitContext.branch||spec.branch||'blue'}-v1`;branchInput.dataset.taskId=task.id}
      $('#git-lease-sha').placeholder=contextComplete?gitContext.remote_head:'40 位远端 commit SHA';
      $('#decision-form').querySelectorAll('textarea,button').forEach(element=>element.disabled=!needs||Boolean(unknownJob)||gitDecision);
      $('#plan-form').querySelectorAll('textarea,button').forEach(element=>element.disabled=!needs||Boolean(unknownJob)||gitDecision);
      const decision=$('#decision');decision.placeholder=needs?'例如：写入 result.txt: 已确认；或：探测 Provider codex_cli: 0token':'只在页面给出明确问题时回答';
      $('#decision-help').textContent=unknownJob?`${task.wait_reason}；只有在 Host Bridge 已明确返回未接收时，才确认 ${unknownJob.id} 未执行。`:gitDecision?(contextComplete?'先阅读下面的原因、SHA、Evidence 与选项影响，再提交精确授权。':'没有原因与证据不能授权；请先运行下面的只读复核。'):canAuthorize?`${task.wait_reason||'Planner 正在等待选择。'}；采用建议方案需要一次明确授权，授权只绑定当前 Task、Spec revision、工作区和 15 分钟有效期。`:needs?`${task.wait_reason||'系统正在等待一个明确决定。'}；请给出页面支持的明确指令，或取消 Task。`:'当前不需要主人决定。';
      renderArtifacts(data);renderJobs(data);renderSessions(data);renderSessionFiles(data);eventRows($('#task-events'),data.events);
    }
    async function openTask(id){currentTask=id;show('task',false);$('#task-notice').textContent='';try{const data=await api(`/api/tasks/${encodeURIComponent(id)}`);if(!data.task)throw new Error('Task 不存在');currentProject=data.project_id;taskBoardData=data;renderScope();renderTaskMetrics(data,taskUsageData);renderGoalRail(data);renderTaskBoard(data);renderTaskDetail(data);$('#task-title').textContent=data.project_name||projectName(data.project_id);$('#context-copy').textContent=`${data.project_name||projectName(data.project_id)} / Task ${id}`}catch(error){renderEmptyInspector(error.message)}}
    async function loadTaskBoard(){if(!currentProject){taskBoardData={tasks:[],goals:[]};$('#task-title').textContent='请选择项目';renderTaskMetrics(taskBoardData,null);renderGoalRail(taskBoardData);renderTaskBoard(taskBoardData);renderEmptyInspector('请从顶部“项目范围”选择项目。选择只会刷新工作台，不会跳转页面。');return}try{const [data,usage]=await Promise.all([api(`/api/projects/${encodeURIComponent(currentProject)}`),api('/api/token')]);taskBoardData=data;taskUsageData=usage;if(currentGoal&&!data.goals.some(item=>item.id===currentGoal))currentGoal=null;if(currentTask&&!data.tasks.some(item=>item.id===currentTask))currentTask=null;const name=data.project_name||projectName(currentProject);$('#task-title').textContent=name;$('#context-copy').textContent=`项目范围 ${name}`;renderTaskMetrics(data,usage);renderGoalRail(data);renderTaskBoard(data);if(currentTask)await openTask(currentTask);else if(currentGoal)renderGoalDetail(data.goals.find(item=>item.id===currentGoal));else if(data.task)await openTask(data.task.id);else renderEmptyInspector('这个项目尚无 Task。可在项目管家提交第一条指令。')}catch(error){taskBoardData={tasks:[],goals:[]};renderGoalRail(taskBoardData);renderTaskBoard(taskBoardData);renderEmptyInspector(error.message)}}
    async function loadButler(){
      const box=$('#butler-messages'),input=$('#butler-message');clear(box);input.disabled=!currentProject;
      if(!currentProject){$('#butler-title').textContent='项目管家';box.append(node('div','empty','请先从项目范围选择一个活动项目。'));return}
      $('#butler-title').textContent=`${projectName(currentProject)} · 项目管家`;
      try{const data=await api(`/api/butler?project_id=${encodeURIComponent(currentProject)}`);if(!data.messages.length){box.append(node('div','empty','还没有消息。'));return}data.messages.forEach(item=>{const row=node('article',`chat-row ${item.role}`),head=node('header');head.append(node('strong','',item.role==='owner'?'主人':'项目管家'),node('time','',time(item.created_at)));row.append(head,node('p','',item.content));box.append(row)});box.scrollTop=box.scrollHeight}catch(error){box.append(node('div','empty',error.message))}
    }
    const formatToken=value=>Number(value||0).toLocaleString('zh-CN');
    const formatRatio=value=>value===null||value===undefined?'—':`${Number(value).toFixed(2)} : 1`;
    function setTokenMetrics(prefix,data){for(const [suffix,keyName] of [['total','total_tokens'],['input','input_tokens'],['cached','cached_input_tokens'],['uncached','uncached_input_tokens'],['output','output_tokens']])$(`#token-${prefix}-${suffix}`).textContent=formatToken(data[keyName])}
    function usageRows(target,rows,labeler){clear(target);if(!rows.length){target.append(node('div','empty','尚无模型消费。'));return}rows.forEach(item=>{const row=node('div','usage-row'),copy=node('span','',labeler(item));copy.append(node('small','',`Input ${formatToken(item.input_tokens)} · Cached ${formatToken(item.cached_input_tokens)} · Uncached ${formatToken(item.uncached_input_tokens)} · Output ${formatToken(item.output_tokens)} · ${item.calls} calls`));row.append(copy,node('strong','',formatToken(item.total_tokens)));target.append(row)})}
    async function loadToken(){
      try{const data=await api('/api/token');setTokenMetrics('all',data.all_history);setTokenMetrics('today',data.today);$('#token-today-title').textContent=`今日 · ${data.today.date}`;$('#ratio-all-io').textContent=formatRatio(data.all_history.ratios.input_per_output);$('#ratio-all-cu').textContent=formatRatio(data.all_history.ratios.cached_per_uncached);$('#ratio-today-io').textContent=formatRatio(data.today.ratios.input_per_output);$('#ratio-today-cu').textContent=formatRatio(data.today.ratios.cached_per_uncached);
        const trend=$('#token-trend');clear(trend);const days=data.trend.slice(-14),maximum=Math.max(1,...days.map(day=>day.total_tokens));days.forEach(day=>{const item=node('div','bar-item'),bar=node('i');bar.style.height=`${Math.max(2,day.total_tokens/maximum*100)}%`;bar.title=`${day.date}: ${formatToken(day.total_tokens)} Token`;item.append(node('strong','',formatToken(day.total_tokens)),bar,node('small','',day.date.slice(5)));trend.append(item)});
        const share=$('#project-share');clear(share);const total=Math.max(1,data.all_history.total_tokens);if(!data.projects.length)share.append(node('div','empty','尚无项目消费。'));data.projects.forEach(item=>{const row=node('div','share-row'),track=node('span','share-track'),fill=node('i');fill.style.width=`${item.total_tokens/total*100}%`;track.append(fill);row.append(node('span','',item.display_name||projectName(item.project_id)),track,node('strong','',`${formatToken(item.total_tokens)} · ${(item.total_tokens/total*100).toFixed(1)}%`));share.append(row)});
        usageRows($('#usage-projects'),data.projects,item=>item.display_name||projectName(item.project_id));usageRows($('#usage-tasks'),data.tasks,item=>item.task_id);usageRows($('#usage-models'),data.models,item=>`${item.model} · ${item.provider_key}`);usageRows($('#usage-sessions'),data.sessions,item=>`${item.task_session_id} · Worker ${item.worker_id} (${item.worker_role})`)
      }catch(error){const box=$('#token-trend');clear(box);box.append(node('div','empty',error.message))}
    }
    async function loadMonitor(){
      try{const data=await api('/api/monitor'),summary=data.summary,total=values=>Object.values(values||{}).reduce((sum,value)=>sum+Number(value||0),0);$('#monitor-project-count').textContent=summary.projects;$('#monitor-archived-count').textContent=`归档 ${summary.archived_projects}`;$('#monitor-task-count').textContent=summary.tasks;$('#monitor-due-count').textContent=summary.due_actions;$('#monitor-lease-count').textContent=summary.active_leases;$('#monitor-session-count').textContent=summary.task_sessions;$('#monitor-job-count').textContent=total(data.host_jobs);$('#monitor-artifact-count').textContent=total(data.artifacts);const ok=data.database.quick_check.length===1&&data.database.quick_check[0]==='ok';$('#monitor-db-status').className=`status-pill ${ok?'status-done':'status-needs_decision'}`;$('#monitor-db-status').textContent=ok?'只读检查通过':'检查异常';
        const facts=$('#monitor-facts');clear(facts);facts.append(fact('Journal',data.database.journal_mode),fact('Quick check',data.database.quick_check.join(', ')),fact('Schema',data.database.schema_version),fact('Tables',data.database.tables),fact('Cronner',data.cronner.mode),fact('唯一入口',data.cronner.entry),fact('Captured',time(data.captured_at)));
        const statuses=$('#monitor-statuses');clear(statuses);for(const name of ['pending','in_progress','done','needs_decision'])statuses.append(fact(label(name),data.task_statuses[name]));
        const projectBox=$('#monitor-projects');clear(projectBox);const active=data.projects.filter(item=>!item.archived_at);if(!active.length)projectBox.append(node('div','empty','没有活动项目。'));active.forEach(item=>{const card=node('article','artifact-card'),head=node('header');head.append(node('strong','',item.display_name||item.project_id),status(item.public_status));card.append(head,node('small','mono',`${item.project_id} · ${item.phase||'—'} · ${item.task_id||'无 Task'} · ${time(item.updated_at)}`));projectBox.append(card)});
        const providers=$('#monitor-providers');clear(providers);data.providers.forEach(provider=>{const latest=provider.latest_probe,result=latest?.result,ready=provider.readiness,card=node('article','artifact-card'),head=node('header'),probeCopy=result?(result.model_invoked?`${result.mode} · ${result.available?'available':'unavailable'} · ${result.total_tokens} Token · ${result.detail}`:`0 Token 版本探活 · 未调用模型 · ${result.available?'CLI available':'CLI unavailable'} · ${result.detail}`):'尚未运行探针';head.append(node('strong','',provider.display_name),status(latest?.public_status||'pending'));card.append(head,node('small','mono',provider.provider_key),node('small','',`installed ${ready.installed===null?'unknown':ready.installed} · CLI ${ready.cli_probe} · resume ${ready.session_resume_ready} · execution ${ready.recent_execution_health}`),node('small','',probeCopy));const actions=node('div','provider-actions'),zero=node('button','','0 Token 探针');zero.addEventListener('click',()=>triggerProbe(provider,'zero'));actions.append(zero);const minimal=node('button','','极小 Token 探针');minimal.disabled=!provider.minimal_token_probe;minimal.title=provider.minimal_token_probe?'会调用一次付费模型，必须再次确认':'该 Adapter 不支持安全的只读极小 Token 探针';minimal.addEventListener('click',()=>triggerProbe(provider,'minimal'));actions.append(minimal);if(latest?.task_id){const open=node('button','','查看 Task');open.addEventListener('click',()=>openTask(latest.task_id));actions.append(open)}card.append(actions);providers.append(card)});
        eventRows($('#monitor-events'),data.recent_events)
      }catch(error){const box=$('#monitor-events');clear(box);box.append(node('div','empty',error.message))}
    }
    async function triggerProbe(provider,mode){
      const notice=$('#probe-notice'),project=`monitor-probe-${provider.provider_key}`;
      let content=`探测 Provider ${provider.provider_key}: 0token`;
      if(mode==='minimal'){const confirmation=prompt(`极小 Token 探针会调用一次 ${provider.display_name}。输入 “${provider.provider_key}” 确认。`);if(confirmation!==provider.provider_key){notice.textContent='未确认，未提交任何模型调用。';return}content=`探测 Provider ${provider.provider_key}: minimal 确认 ${confirmation}`}
      try{await api('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:project,content,idempotency_key:key()})});notice.textContent=`${provider.display_name} ${mode==='zero'?'0 Token':'极小 Token'}探针已作为 Task 入队。`;await loadProjects()}catch(error){notice.textContent=error.message}
    }
    async function archiveCurrentProject(){
      if(!currentProject)return;
      const name=projectName(currentProject);
      const confirmation=prompt(`输入项目名称“${name}”确认归档。历史和文件不会删除。`);
      if(confirmation!==name)return;
      const notice=$('#project-notice');
      try{await api('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'archive_project',project_id:currentProject,confirmation:currentProject,idempotency_key:key()})});notice.textContent=`${name} 已归档，历史完整保留。`;currentProject=null;currentTask=null;$('#project-title').textContent='项目';clear($('#project-detail'));$('#project-detail').append(node('article','panel empty','项目已归档。'));await loadProjects()}catch(error){notice.textContent=error.message}
    }
    async function loadSettings(){try{const data=await api('/api/settings-library');const settings=$('#settings-data');clear(settings);if(!data.settings.length)settings.append(node('div','empty','没有设置。'));data.settings.forEach(item=>{const row=node('div','setting-row'),scope=item.scope==='project'?`项目 ${projectName(item.project_id)}`:'全局';row.append(node('strong','',`${scope} · ${item.setting_key}`),node('code','',JSON.stringify(item.value)),node('span','',item.source));settings.append(row)});const library=$('#library-data');clear(library);if(!data.library.length)library.append(node('div','empty','资源库为空。'));data.library.forEach(item=>{const card=node('article','library-card');const head=node('header');head.append(node('h2','',`${item.kind} / ${item.item_key}`),node('small',item.sha256_matches?'ok-text':'warning-text',item.sha256_matches?'SHA 匹配':'SHA 不匹配'));card.append(head,node('code','',item.path),node('small','mono',`revision ${item.revision} · ${item.sha256}`));library.append(card)})}catch(error){const box=$('#settings-data');clear(box);box.append(node('div','empty',error.message))}}
    async function postAction(kind,instruction='',plan){if(!currentTask||!currentProject)throw new Error('请先选择项目和 Task');return api('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:currentProject,task_id:currentTask,kind,instruction,plan,idempotency_key:key()})})}
    $('#project-scope').addEventListener('change',async event=>{currentProject=event.target.value||null;currentTask=null;currentGoal=null;taskBoardData=null;taskUsageData=null;renderScope();$('#context-copy').textContent=currentProject?`项目范围 ${projectName(currentProject)}`:'全部项目';if(!$('#task').hidden)await loadTaskBoard();else if(!$('#project-butler').hidden)await loadButler();else if(!$('#project').hidden&&currentProject)await openProject(currentProject);else if(!$('#token').hidden)await loadToken();else if(!$('#monitor').hidden)await loadMonitor()});
    $('#scope-open-project').addEventListener('click',()=>{if(currentProject)openProject(currentProject)});
    $('#goal-all').addEventListener('click',()=>{currentGoal=null;currentTask=null;if(taskBoardData){renderGoalRail(taskBoardData);renderTaskBoard(taskBoardData);renderEmptyInspector('已显示这个项目的全部 Task。请选择泳道卡片查看详情。')}});
    $('#goal-history-toggle').addEventListener('click',()=>{const box=$('#goal-done-list');box.hidden=!box.hidden;$('#goal-history-toggle').setAttribute('aria-expanded',String(!box.hidden))});
    $('#refresh').addEventListener('click',async()=>{const button=$('#refresh');button.disabled=true;button.textContent='刷新中';await Promise.all([loadHealth(),loadProjects()]);if(!$('#task').hidden)await loadTaskBoard();else if(currentProject&&!$('#project').hidden)await openProject(currentProject);else if(!$('#project-butler').hidden)await loadButler();else if(!$('#token').hidden)await loadToken();else if(!$('#monitor').hidden)await loadMonitor();button.disabled=false;button.textContent='刷新'});
    $('#message-form').addEventListener('submit',async event=>{event.preventDefault();const notice=$('#home-notice');try{const explicit=$('#project-id').value.trim(),body={content:$('#message').value,idempotency_key:key()};if(explicit)body.project_id=explicit;const routed=await api('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});currentProject=routed.project_id;notice.textContent=routed.routed_only?`已定位 ${projectName(currentProject)}，没有创建 Task。`:`已路由到 ${projectName(currentProject)} 并进入 SQLite 队列；Cronner 将自动推进。`;await loadProjects();await loadButler()}catch(error){notice.textContent=error.message}});
    $('#butler-form').addEventListener('submit',async event=>{event.preventDefault();const notice=$('#butler-notice');if(!currentProject){notice.textContent='请先选择项目。';return}try{await api('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:currentProject,content:$('#butler-message').value,idempotency_key:key()})});notice.textContent='已进入项目消息历史；Cronner 将自动推进。';$('#butler-message').value='';await loadButler();await loadProjects()}catch(error){notice.textContent=error.message}});
    $('#setting-form').addEventListener('submit',async event=>{event.preventDefault();const notice=$('#setting-notice'),value=Number($('#setting-value').value);if(!currentProject){notice.textContent='请先从顶部选择项目范围。';return}if(!Number.isInteger(value)){notice.textContent='设置值必须是整数。';return}try{await api('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'set_project_setting',project_id:currentProject,setting_key:$('#setting-key').value,value,idempotency_key:key()})});notice.textContent='设置意图已入队；Cronner 将在后续 Tick 生效，新 TaskSession 会冻结来源。';await loadSettings()}catch(error){notice.textContent=error.message}});
    $('#provider-order-form').addEventListener('submit',async event=>{event.preventDefault();const notice=$('#provider-order-notice'),role=$('#provider-role').value,providers=$('#provider-order').value.split(',').map(value=>value.trim()).filter(Boolean);if(!currentProject){notice.textContent='请先选择项目范围。';return}try{await api('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'set_project_setting',project_id:currentProject,setting_key:'provider_order',value:{[role]:providers},idempotency_key:key()})});notice.textContent='Provider 顺序已入队；只影响后续创建的 TaskSession。'}catch(error){notice.textContent=error.message}});
    $('#project-rule-form').addEventListener('submit',async event=>{event.preventDefault();const notice=$('#project-rule-notice');if(!currentProject){notice.textContent='请先选择项目范围。';return}try{await api('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'set_project_rule',project_id:currentProject,rule_key:$('#project-rule-key').value,content:$('#project-rule-content').value,idempotency_key:key()})});notice.textContent='项目规则已入队；Cronner 生效后写入版本化资源库。'}catch(error){notice.textContent=error.message}});
    $('#create-project-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type="submit"]'),name=$('#new-project-name').value,hostPath=$('#new-project-path').value.trim(),notice=$('#project-notice'),idempotencyKey=key();button.disabled=true;try{const result=await api('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'create_project',display_name:name,host_path:hostPath||undefined,idempotency_key:idempotencyKey})});const copy={created:'已创建',restored:'已恢复',bound:'已绑定',unchanged:'未变化，未重复写入历史'};notice.textContent=`${name}：${copy[result.result]||result.result}。`;currentProject=result.project_id;await loadProjects();await openProject(result.project_id)}catch(error){notice.textContent=error.message}finally{button.disabled=false}});
    $('#search-form').addEventListener('submit',async event=>{event.preventDefault();const box=$('#search-results');clear(box);try{const data=await api(`/api/search?q=${encodeURIComponent($('#search').value)}`);if(!data.results?.length){box.append(node('div','empty','没有匹配结果。'));return}data.results.forEach(item=>{const row=node('div','search-result');row.append(node('span','status-pill',item.kind),node('strong','',item.detail||item.ref),node('code','',`${projectName(item.project_id)} ${item.status||''}`));box.append(row)})}catch(error){box.append(node('div','empty',error.message))}});
    $('#wake-task').addEventListener('click',async()=>{try{await postAction('wake');$('#task-notice').textContent='唤醒意图已入队；仍由 Cronner 调用唯一 advance_project。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#authorize-plan').addEventListener('click',async()=>{if(!window.confirm(`明确授权采用当前 Planner 方案？授权只绑定 Task ${currentTask} 的当前 revision 和工作区，15 分钟后失效。`))return;try{await postAction('authorize',currentTask);$('#task-notice').textContent='绑定范围的授权已入队；Cronner 将在后续 Tick 应用。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#confirm-not-executed').addEventListener('click',async event=>{const jobId=event.currentTarget.dataset.jobId;if(!jobId||!window.confirm(`仅当 Host Bridge 已明确返回未接收时继续。确认 HostJob ${jobId} 没有执行？`))return;try{await postAction('confirm_not_executed',jobId);$('#task-notice').textContent='未执行确认已入队；Cronner 将安全终结这个 Task。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#refresh-git-context').addEventListener('click',async()=>{try{await postAction('refresh_git_publish_context');$('#task-notice').textContent='只读复核已入队；Cronner 将通过 HostJob 读取本地与远端事实，不会 push。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#git-new-branch-form').addEventListener('submit',async event=>{event.preventDefault();const branch=$('#git-new-branch').value.trim();if(!window.confirm(`明确授权把当前 Task revision 发布到新分支 ${branch}？授权 15 分钟后失效。`))return;try{await postAction('publish_new_branch',branch);$('#task-notice').textContent='新分支发布授权已入队；Cronner 将按新 Spec revision 推进。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#git-force-form').addEventListener('submit',async event=>{event.preventDefault();const sha=$('#git-lease-sha').value.trim();if(!window.confirm(`这会改写目标分支。仅当远端仍为 ${sha} 时覆盖，是否明确授权？`))return;try{await postAction('force_publish_with_lease',sha);$('#task-notice').textContent='force-with-lease 授权已入队；远端 SHA 变化时仍会安全拒绝。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#cancel-task').addEventListener('click',async()=>{try{await postAction('cancel');$('#task-notice').textContent='取消已入队。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#rerun-task').addEventListener('click',async()=>{try{await postAction('rerun');$('#task-notice').textContent='重新执行已入队。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#decision-form').addEventListener('submit',async event=>{event.preventDefault();try{await postAction('provide_decision',$('#decision').value);$('#task-notice').textContent='决定已入队。'}catch(error){$('#task-notice').textContent=error.message}});
    $('#plan-form').addEventListener('submit',async event=>{event.preventDefault();try{await postAction('provide_plan','',JSON.parse($('#plan').value));$('#task-notice').textContent='计划已入队。'}catch(error){$('#task-notice').textContent=error.message}});
    loadHealth();loadProjects();
    setInterval(()=>{if(document.hidden)return;if(!$('#task').hidden)loadTaskBoard();else if(!$('#monitor').hidden)loadMonitor()},3000);
  </script>
</body>
</html>
"""
